
resources:
  containers:
  - container: main_container
    image: golang
  - container: mongodb
    image: mongo:latest

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: main_container

services:
  mongodb: mongodb

variables:
  mongodb_uri: 'mongodb://mongodb:27017'

steps:
#- task: GoTool@0
#  inputs:
#    version: '1.13.5'
#- script: apt install ca-certificates
#- task: Go@0
# inputs:
#   command: 'get'
#   arguments: '-d'
#   workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: Unit and integration tests
  inputs:
    command: 'test'
    arguments: '-p 1 ./...'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
#- task: Docker@2
#  displayName: Build and push an image to container registry
#  inputs:
#    command: buildAndPush
#    repository: piot/piot-server
#    containerRegistry: docker-hub
#    tags: |
#      latest
