version: "3"

services:

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  prometheus-base:
    image: prom/prometheus
    container_name: prometheus-base
    restart: always
    volumes:
        - ./prometheus-base/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus-base:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: "104"
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_SERVER_DOMAIN: 'iot2.pavoucek.net'
      GF_SERVER_ROOT_URL: '%(protocol)s://%(domain)s/grafana/'
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_HOST: 'mail.pavoucek.net:25'
      GF_SMTP_FROM_ADDRESS: 'nezerka@betulapendula.com'
      GF_SMTP_FROM_NAME: 'Monitoring'
      GF_SMTP_USER: 'nezerka@betulapendula.com'
      GF_SMTP_PASSWORD: 'xxx'

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-passwd:/etc/nginx/.htpasswd
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  mqtt:
    build: ./mosquitto
    image: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/conf:/etc/mosquitto

  mqtt-exporter:
    image: sapcc/mosquitto-exporter:0.6.0
    environment:
      BROKER_ENDPOINT: tcp://mqtt:1883
      MQTT_USER: mon
      MQTT_PASS: mon

volumes:
    prometheus-base:
    grafana:
